//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ObjectId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> Department { get; set; }
        public string InventoryNumber { get; set; }
        public int AmountObjects { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual ObjectType ObjectType1 { get; set; }
    }
}
